services:
  db:
    container_name: database
    image: postgres:15.3-alpine3.18
    ports:
      - 5432:5432
    networks:
      - default
    env_file:
      - .postgres_env

  nginx:
    container_name: nginx
    image: nginx:1.25.1-alpine
    ports:
      - 8090:80
    networks:
      - default

  cd:
    container_name: jenkins
    image: sousandre/jenkins-docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/var/jenkins_home
    ports:
      - 8080:8080
    networks:
      - default

  #node:
  #  container_name: api_node
  #  privileged: true
  #  volumes:
  #    - /lib/modules:/lib/modules:ro
  #    - /sys:/sys:ro
  #    - /usr/src:/usr/src:ro
  #  build:
  #    dockerfile: NodeDockerfile
  #  ports:
  #    - 8081:8081
  #  networks:
  #    - default
#
  #python:
  #  container_name: api_python
  #  privileged: true
  #  volumes:
  #    - /lib/modules:/lib/modules:ro
  #    - /sys:/sys:ro
  #    - /usr/src:/usr/src:ro
  #  build:
  #    dockerfile: PythonDockerfile
  #  ports:
  #    - 8082:8082
  #  networks:
  #    - default

networks:
  default:
    driver: bridge


volumes:
  jenkins_data: