services:
  db:
    container_name: database
    image: postgres:15.3-alpine3.18
    ports:
      - 5432:5432
    networks:
      - default
    env_file:
      - .postgres_env

  nginx:
    container_name: nginx
    image: nginx:1.25.1-alpine
    volumes:
      - ./volumes/nginx/conf.d/:/etc/nginx/conf.d/:ro
    ports:
      - 8090:80
    networks:
      - default

  cd:
    container_name: jenkins
    image: jenkins/jenkins:lts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/var/jenkins_home
    ports:
      - 8080:8080
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  jenkins_data: